spring:
  profiles:
    active: ${HOUSE_ENV}
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    http:
      encoding:
        charset: UTF-8
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#默认UTF-8

server:
  port: 8080
  servlet:
    context-path: /house

mybatis:
  mapper-locations: classpath:mapper/*.xml  #对应mapper映射xml文件的所在路径
#  type-aliases-package: com.babyjuan.house.repository.entity # 对应实体类的路径非必须

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

lianjia:
  city:
    rent:
      root: https://nj.lianjia.com/zufang/
    name: 南京
    second:
      hand:
        root: https://sh.lianjia.com/ershoufang/
        name: 上海
    sh:
      deal:
        root: https://sh.lianjia.com/chengjiao/
        name: 上海


spider:
  retryTimes: 3
  sleepTime: 200
  threadnum: 1
  proxy:
    xiciRoot: http://www.xicidaili.com/nn/
    mimiipRoot: http://www.mimiip.com/gngao/
    file: ./logs/proxy.txt
